### ISSUE TITLE
No fade transition effect in IE8

### ISSUE THREAD

**Issue by andygott** [andygott/Really-Simple-Slideshow#7]
In IE8 the fade effect during transitions between slides is broken  – fade transitions always appear as if the effect option were set to 'none'. Slide effects work. Currently working on a fix for this.

**Comment by andygott** [comment]
There's a very simple fix for this (I love it when it's easy!) – just a couple of extra lines of CSS:

[Updated: removed opacity: inherit – this caused strange behavior in chrome]

``` css
.rs-slideshow .slide-container img,
.rs-slideshow .slide-container .slide-caption,
.rs-slideshow .slide-container a {
    filter: inherit;
}
```

I'll push this to Github later today.
